services:
  redis:
    image: redis:7.4-rc2-alpine
    container_name: api-redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: api-postgres
    environment:
      POSTGRES_USER: "myUser"
      POSTGRES_PASSWORD: "myPassword"
      POSTGRES_DB: "myDatabase"
    ports:
      - "5000:5432"

